baseURL = "https://claire-zeng.github.io/blog/"
languageCode = "zh-cn"
title = "Claire的技术学习笔记"
theme = "modern-tech-theme"

# 环境配置
[params]
  description = "记录技术学习历程，分享编程心得与算法思考"
  author = "Claire-zeng"
  github = "https://github.com/Claire-zeng"
  subtitle = "探索技术之美，记录学习之路"
  
  # 部署环境配置
  [params.deploy]
    # 本地开发环境
    local = false
    # GitHub Pages环境
    github = true

[menu]
  [[menu.main]]
    identifier = "home"
    name = "首页"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "categories"
    name = "分类"
    url = "/categories/"
    weight = 2
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 4

[markup]
  [markup.highlight]
    style = "tomorrow"
    lineNos = false
    lineNumbersInTable = false
    noClasses = false
    noHl = false
    hlLines = ""
    hlInverse = false

# GitHub Pages 配置
[build]
  writeStats = true
