# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Numerical Theme"
license = "MIT"
licenselink = "https://github.com/yourname/numerical-theme/blob/master/LICENSE"
description = "A modern Hugo theme for numerical optimization and mathematical content"
homepage = "https://example.com/"
tags = ["mathematics", "optimization", "academic", "responsive"]
features = ["mathematical-formulas", "code-highlighting", "responsive-design"]
min_version = "0.80.0"

[author]
  name = "Your Name"
  homepage = "https://example.com/"

# If porting an existing theme
[original]
  name = "Numerical Theme"
  homepage = "https://github.com/yourname/numerical-theme"
  repo = "https://github.com/yourname/numerical-theme"
